name: Publish Python 🐍 distribution 📦 to PyPI

on:
  push:
    tags:
      - 'v*'
      - 'V*'  # Handles both lowercase and uppercase version tags

jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install build tools
      run: python -m pip install --upgrade build twine

    - name: Build package
      run: python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}