#!/usr/bin/env python3
"""
DREDGE OAuth Setup - Interactive Configuration

This script helps you configure GitHub and Google OAuth credentials.
"""

import os
import sys
import secrets
from pathlib import Path


def generate_secret_key():
    """Generate a secure SECRET_KEY."""
    return secrets.token_hex(32)


def print_header(text):
    """Print a formatted header."""
    print("\n" + "=" * 80)
    print(f"  {text}")
    print("=" * 80 + "\n")


def print_step(number, title):
    """Print a step header."""
    print(f"\n{'='*80}")
    print(f"STEP {number}: {title}")
    print("=" * 80 + "\n")


def github_setup():
    """Print GitHub OAuth setup instructions."""
    print_step(1, "SETUP GITHUB OAUTH")
    
    print("""
Follow these steps to create a GitHub OAuth App:

1. Go to GitHub Settings:
   https://github.com/settings/developers

2. Click "New OAuth App" in the "OAuth Apps" section

3. Fill in the Application details:
   
   Application name:
      DREDGE Studio
   
   Homepage URL:
      http://localhost:3000
   
   Application description:
      AI-powered security and development platform
   
   Authorization callback URL:
      http://localhost:3000/auth/github/callback

4. Click "Register application"

5. You'll see your credentials:
   - Client ID (copy this)
   - Client Secret (click "Generate a new client secret")

6. Keep these safe!
""")
    
    client_id = input("\n📝 Paste your GitHub Client ID: ").strip()
    client_secret = input("📝 Paste your GitHub Client Secret: ").strip()
    
    return {
        "GITHUB_CLIENT_ID": client_id,
        "GITHUB_CLIENT_SECRET": client_secret,
    }


def google_setup():
    """Print Google OAuth setup instructions."""
    print_step(2, "SETUP GOOGLE OAUTH")
    
    print("""
Follow these steps to create Google OAuth credentials:

1. Go to Google Cloud Console:
   https://console.developers.google.com/

2. Create a new project:
   - Click "Select a project" at the top
   - Click "NEW PROJECT"
   - Name it "DREDGE Studio"
   - Click "Create"

3. Enable Google+ API:
   - Go to "APIs & Services" → "Library"
   - Search for "Google+ API"
   - Click it → Click "Enable"

4. Create OAuth 2.0 Credentials:
   - Go to "APIs & Services" → "Credentials"
   - Click "Create Credentials" → "OAuth 2.0 Client ID"
   - Choose "Web Application"
   - Fill in:
     Name: DREDGE Studio Web Client

5. Configure Authorized URIs:
   - Authorized JavaScript origins:
     http://localhost:3000
   
   - Authorized redirect URIs:
     http://localhost:3000/auth/google/callback

6. Click "Create"

7. Copy your credentials:
   - Client ID (ends with .apps.googleusercontent.com)
   - Client Secret
""")
    
    client_id = input("\n📝 Paste your Google Client ID: ").strip()
    client_secret = input("📝 Paste your Google Client Secret: ").strip()
    
    return {
        "GOOGLE_CLIENT_ID": client_id,
        "GOOGLE_CLIENT_SECRET": client_secret,
    }


def create_env_file(config):
    """Create or update .env file with configuration."""
    print_step(3, "CREATE .ENV FILE")
    
    env_content = f"""# DREDGE Studio - OAuth Configuration
# Generated by oauth_setup.py

# Flask Configuration
FLASK_ENV=production
SECRET_KEY={config['SECRET_KEY']}

# GitHub OAuth
GITHUB_CLIENT_ID={config.get('GITHUB_CLIENT_ID', '')}
GITHUB_CLIENT_SECRET={config.get('GITHUB_CLIENT_SECRET', '')}

# Google OAuth
GOOGLE_CLIENT_ID={config.get('GOOGLE_CLIENT_ID', '')}
GOOGLE_CLIENT_SECRET={config.get('GOOGLE_CLIENT_SECRET', '')}

# OAuth Redirect
OAUTH_REDIRECT_BASE=http://localhost:3000

# Server Configuration
FLASK_HOST=0.0.0.0
FLASK_PORT=3000
"""
    
    env_path = Path(".env")
    
    if env_path.exists():
        print("⚠️  .env file already exists")
        overwrite = input("Overwrite? (y/N): ").strip().lower()
        if overwrite != "y":
            print("Skipping .env creation")
            return False
    
    with open(env_path, "w") as f:
        f.write(env_content)
    
    print(f"✅ Created .env file")
    return True


def verify_setup():
    """Verify the setup."""
    print_step(4, "VERIFY SETUP")
    
    # Load environment
    env_path = Path(".env")
    if env_path.exists():
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#"):
                    if "=" in line:
                        key, value = line.split("=", 1)
                        os.environ[key.strip()] = value.strip()
    
    print("Configuration Status:\n")
    
    secret_key = os.environ.get("SECRET_KEY", "")
    github_id = os.environ.get("GITHUB_CLIENT_ID", "")
    github_secret = os.environ.get("GITHUB_CLIENT_SECRET", "")
    google_id = os.environ.get("GOOGLE_CLIENT_ID", "")
    google_secret = os.environ.get("GOOGLE_CLIENT_SECRET", "")
    
    print(f"  SECRET_KEY:           {'✅' if secret_key else '❌'} {'SET' if secret_key else 'NOT SET'}")
    print(f"  GitHub Client ID:     {'✅' if github_id else '❌'} {'SET' if github_id else 'NOT SET'}")
    print(f"  GitHub Client Secret: {'✅' if github_secret else '❌'} {'SET' if github_secret else 'NOT SET'}")
    print(f"  Google Client ID:     {'✅' if google_id else '❌'} {'SET' if google_id else 'NOT SET'}")
    print(f"  Google Client Secret: {'✅' if google_secret else '❌'} {'SET' if google_secret else 'NOT SET'}")
    
    if all([secret_key, github_id, github_secret, google_id, google_secret]):
        print("\n✅ All credentials configured!")
        return True
    else:
        print("\n⚠️  Some credentials are missing")
        return False


def main():
    """Main CLI entry point."""
    print_header("DREDGE OAUTH SETUP")
    
    print("This wizard will help you set up GitHub and Google OAuth")
    print("for DREDGE Studio authentication.\n")
    
    # Generate SECRET_KEY
    print_step(0, "GENERATE SECRET KEY")
    secret_key = generate_secret_key()
    print(f"Generated SECRET_KEY:\n  {secret_key}\n")
    print("✅ This will be saved to .env\n")
    
    config = {"SECRET_KEY": secret_key}
    
    # GitHub Setup
    try:
        github_config = github_setup()
        config.update(github_config)
        print("\n✅ GitHub credentials saved")
    except Exception as e:
        print(f"\n❌ GitHub setup failed: {e}")
    
    # Google Setup
    try:
        google_config = google_setup()
        config.update(google_config)
        print("\n✅ Google credentials saved")
    except Exception as e:
        print(f"\n❌ Google setup failed: {e}")
    
    # Create .env file
    create_env_file(config)
    
    # Verify
    if verify_setup():
        print("\n" + "=" * 80)
        print("NEXT STEPS")
        print("=" * 80 + "\n")
        
        print("""
1. Load environment variables:
   
   cd dredge-cli-repo
   export $(cat .env | xargs)

2. Start DREDGE server:
   
   python -m dredge.server

3. Open in browser:
   
   http://localhost:3000/auth/login

4. You should see "Sign in with GitHub" and "Sign in with Google" buttons

5. Click either button to test the OAuth flow
""")
    
    print("=" * 80)
    print("✅ Setup Complete!")
    print("=" * 80 + "\n")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n⚠️  Setup cancelled by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Setup failed: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
