const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const {JSDOM}=require('jsdom');
function setup(autoPause=true){const d=new JSDOM(fs.readFileSync('src/dredge/static/studio_pilot.html','utf8'),{url:'https://example.test/pilot-demo',runScripts:'outside-only',pretendToBeVisual:true});const w=d.window;let now=0;let timer=null;w.performance.now=()=>now;w.setInterval=fn=>{assert.equal(timer,null,'only one playback timer');timer=fn;return 1;};w.clearInterval=()=>{timer=null;};w.fetch=()=>{throw Error('No network calls allowed');};w.eval(fs.readFileSync('src/dredge/static/studio_pilot.js','utf8'));if(autoPause)w.document.getElementById('play').click();return {d,w,click:id=>w.document.getElementById(id).click(),tick:ms=>{now+=ms;if(timer)timer();},running:()=>timer!==null};}
test('ten fictional scenes, no forms, prepared states and captions',()=>{const s=setup(),doc=s.w.document;assert.equal(doc.querySelectorAll('#scene-list button').length,10);assert.equal(doc.querySelectorAll('form').length,0);assert.match(doc.body.textContent,/Fictional training/);s.click('next');assert.equal(doc.activeElement.id,'scene-title');assert.match(doc.querySelector('#stage').textContent,/\$900/);assert.match(doc.querySelector('#stage').textContent,/\$950/);for(let i=0;i<5;i++)s.click('next');assert.match(doc.querySelector('#stage').textContent,/Pending independent review/);s.d.window.close();});
test('play pause resume restart and navigation clear timers',()=>{const s=setup();s.click('play');assert.ok(s.running());s.tick(3000);s.click('play');assert.equal(s.running(),false);const caption=s.w.document.getElementById('caption').textContent;s.tick(100000);assert.equal(s.w.document.getElementById('caption').textContent,caption);s.click('play');s.click('next');assert.equal(s.running(),false);s.click('restart');assert.match(s.w.document.getElementById('scene-title').textContent,/Welcome/);s.d.window.close();});
test('backgrounding pauses and does not silently resume',()=>{const s=setup();s.click('play');Object.defineProperty(s.w.document,'hidden',{value:true,configurable:true});s.w.document.dispatchEvent(new s.w.Event('visibilitychange'));assert.equal(s.running(),false);Object.defineProperty(s.w.document,'hidden',{value:false,configurable:true});s.w.document.dispatchEvent(new s.w.Event('visibilitychange'));assert.equal(s.running(),false);s.d.window.close();});
test('autoplay finishes, replay works, speed remains bounded',()=>{const s=setup();s.click('play');for(let i=0;i<400;i++)s.tick(5000);assert.equal(s.running(),false);assert.match(s.w.document.getElementById('play-state').textContent,/Finished/);s.click('restart');assert.ok(s.running());s.d.window.close();});

test('mobile scene strip does not wrap and playback has no network APIs',()=>{const css=fs.readFileSync('src/dredge/static/studio_pilot.css','utf8');assert.match(css,/#scene-list\{flex-direction:row;flex-wrap:nowrap;min-width:0;overflow:auto/);const s=setup();s.click('play');assert.equal(s.w.document.activeElement.id,'scene-title');s.w.dispatchEvent(new s.w.Event('pagehide'));assert.equal(s.running(),false);s.d.window.close();});

test('playback status is not repeatedly announced on timer ticks',async()=>{const s=setup();s.click('play');let changes=0;const observer=new s.w.MutationObserver(records=>{changes+=records.length;});observer.observe(s.w.document.getElementById('play-state'),{childList:true});for(let i=0;i<4;i++)s.tick(250);await Promise.resolve();assert.equal(changes,0);observer.disconnect();s.d.window.close();});
test('default run finishes around 8m20s and Replay starts first scene',()=>{const s=setup();s.click('play');s.tick(499000);assert.ok(s.running());s.tick(1000);assert.equal(s.running(),false);assert.equal(s.w.document.getElementById('progress').value,100);s.click('play');assert.ok(s.running());assert.match(s.w.document.getElementById('scene-title').textContent,/Welcome/);s.d.window.close();});
test('pace selection changes elapsed progression and invalid values use default',()=>{for(const [pace,ratio] of [['0.8',0.8],['1.25',1.25],['invalid',1]]){const normal=setup(),changed=setup();normal.click('play');changed.click('play');const select=changed.w.document.getElementById('pace');select.value=pace;select.dispatchEvent(new changed.w.Event('change'));changed.click('play');normal.tick(1000);changed.tick(1000);assert.ok(Math.abs(changed.w.document.getElementById('progress').value/normal.w.document.getElementById('progress').value-ratio)<0.001);normal.d.window.close();changed.d.window.close();}});

test('script initialization enables playback and hides static fallback notice',()=>{const s=setup();const d=s.w.document;assert.equal(d.getElementById('play').disabled,false);assert.equal(d.getElementById('pace').disabled,false);assert.equal(d.getElementById('demo-readiness').hidden,true);assert.equal(d.querySelectorAll('#scene-list p').length,0);assert.equal(d.getElementById('previous').disabled,true);s.d.window.close();});

test('visible page automatically plays all ten scenes without user clicks',()=>{const s=setup(false);assert.ok(s.running());assert.equal(s.w.document.getElementById('play').textContent,'Pause');const seen=new Set([s.w.document.getElementById('scene-number').textContent]);for(let i=0;i<501;i++){s.tick(1000);seen.add(s.w.document.getElementById('scene-number').textContent);}assert.equal(seen.size,10);assert.equal(s.running(),false);assert.match(s.w.document.getElementById('play-state').textContent,/Finished/);s.click('restart');assert.ok(s.running());assert.match(s.w.document.getElementById('scene-title').textContent,/Welcome/);s.d.window.close();});
test('compact layout keeps labels and short captions available during autonomous playback',()=>{const s=setup(false),d=s.w.document;assert.equal(d.querySelector('.demo-intro').tagName,'DETAILS');assert.equal(d.querySelector('.demo-intro').open,false);assert.match(d.querySelector('.player-boundary').textContent,/Fictional training.*Captions only/);for(let i=0;i<500;i++){s.tick(1000);assert.ok(d.getElementById('caption').textContent.trim().split(/\s+/).length<=36);}const css=fs.readFileSync('src/dredge/static/studio_pilot.css','utf8');assert.match(css,/height:100svh/);assert.match(css,/#stage\{flex:1;min-height:60px;overflow:auto/);s.d.window.close();});
test('opening the introduction pauses the automated story',async()=>{const s=setup(false);const intro=s.w.document.querySelector('.demo-intro');intro.open=true;await new Promise(resolve=>s.w.setTimeout(resolve,0));assert.equal(s.running(),false);assert.match(s.w.document.getElementById('play-state').textContent,/Paused for the introduction/);s.d.window.close();});

test('balanced caption splitting avoids tiny unreadable orphan fragments',()=>{const s=setup(false);for(let i=0;i<5000;i++){s.tick(100);const count=s.w.document.getElementById('caption').textContent.trim().split(/\s+/).length;assert.ok(count>=5&&count<=36,`caption has ${count} words`);}s.d.window.close();});

test('scrolling evidence and captions are keyboard reachable and pause for inspection',()=>{for(const id of ['stage','caption']){const s=setup(false);const node=s.w.document.getElementById(id);assert.equal(node.tabIndex,0);assert.equal(node.getAttribute('role'),'region');assert.ok(node.getAttribute('aria-label'));node.focus();assert.equal(s.running(),false);assert.match(s.w.document.getElementById('play-state').textContent,/Paused for inspection/);s.d.window.close();}});
