apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dredge-default-deny
  namespace: dredge
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dredge-internal
  namespace: dredge
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: dredge-cli
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: dredge-cli
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: dredge-cli
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
